### ISSUE TITLE
Missing tests 😢 

### ISSUE THREAD

**Issue by fatso83** [nanosoftonline/clean-mvvm-react#1]
This repository is linked to from the Medium article by Paul Allies and is supposed to present a good case for how a MVVM model is more testable. I am all for that, but this really does not make for such a convincing case when I fail to find a single test in the entire repo.

A lot of the comments on the article is about testing, and so is the article, so until tests are added I find this to be a lost opportunity to show the actual benefits. I also think the README could point to the Medium article for context.

---

That being said, I know that this absolutely a step in the right direction on almost any project, and I have taken the classes by Pete Herd (LogicRoom) on creating frontends that really scale well, and that approach is quite aligned with this (just taken to another level with Functional Reactive Programming). Their Ultra Fast Testing Architecture is a kind of blend of MVVM and MVP and tries to avoid being framework specific, so one big difference is in how the view model is loaded and updated. That would typically look something like this:
```javascript
useEffect(() => {
   await presenter.load( vm => setViewModel(vm) );  
});
``` 
The Presenter and up (concentric architecture) would have no React bindings (such as `setState` or hooks) and are thus trivially testable. It was actually this bit I was wondering how you would implement ... hence the tears .. 😄

**Comment by nanosoftonline** [comment]
Thanks for the interest and the great feedback.  I've updated the repo  and added a few tests

**Comment by nanosoftonline** [comment]
> This repository is linked to from the Medium article by Paul Allies and is supposed to present a good case for how a MVVM model is more testable. I am all for that, but this really does not make for such a convincing case when I fail to find a single test in the entire repo.
> 
> A lot of the comments on the article is about testing, and so is the article, so until tests are added I find this to be a lost opportunity to show the actual benefits. I also think the README could point to the Medium article for context.
> 
> That being said, I know that this absolutely a step in the right direction on almost any project, and I have taken the classes by Pete Herd (LogicRoom) on creating frontends that really scale well, and that approach is quite aligned with this (just taken to another level with Functional Reactive Programming). Their Ultra Fast Testing Architecture is a kind of blend of MVVM and MVP and tries to avoid being framework specific, so one big difference is in how the view model is loaded and updated. That would typically look something like this:
> 
> ```js
> useEffect(() => {
>    await presenter.load( vm => setViewModel(vm) );  
> });
> ```
> 
> The Presenter and up (concentric architecture) would have no React bindings (such as `setState` or hooks) and are thus trivially testable. It was actually this bit I was wondering how you would implement ... hence the tears .. 😄

Thanks for the great feedback, I appreciate it. I've updated the repo and added a few tests
